# clinical_report.py

from datetime import datetime


def generate_clinical_report(severity_label: str, confidence: float) -> str:
    """
    Generate a structured clinical-style report for Diabetic Retinopathy severity.

    Args:
        severity_label (str): Predicted DR severity class.
        confidence (float): Model confidence in the predicted class (0–1).

    Returns:
        str: Multi-section text report.
    """

    severity_label_clean = (severity_label or "").strip()

    # Map severity to description and suggested action
    severity_info = {
        "No DR": {
            "description": "No apparent diabetic retinopathy. Retinal structures appear within normal limits on the analyzed image.",
            "action": "Continue routine diabetes care and schedule regular eye examinations as per standard guidelines (typically every 12–24 months).",
            "urgency": "Routine"
        },
        "Mild": {
            "description": "Early non-proliferative diabetic retinopathy with the presence of microaneurysms and minimal retinal changes.",
            "action": "Recommend comprehensive dilated eye examination and monitoring of glycemic control. Follow-up is usually advised within 6–12 months, or as per local guidelines.",
            "urgency": "Low to Moderate"
        },
        "Moderate": {
            "description": "Non-proliferative diabetic retinopathy with more numerous microaneurysms, hemorrhages, and possible exudates.",
            "action": "Ophthalmology evaluation is recommended. Follow-up typically within 3–6 months for detailed assessment and management planning.",
            "urgency": "Moderate"
        },
        "Severe": {
            "description": "Severe non-proliferative diabetic retinopathy with extensive retinal changes and a high risk of progression to proliferative disease.",
            "action": "Urgent referral to an ophthalmologist is advised for detailed evaluation and potential intervention. Follow-up is generally required within 4–6 weeks.",
            "urgency": "High"
        },
        "Proliferative": {
            "description": "Proliferative diabetic retinopathy characterized by abnormal neovascularization and/or high-risk features that may threaten vision.",
            "action": "Immediate ophthalmology referral is strongly recommended. Timely intervention (e.g., laser therapy, intravitreal injections, or surgery) may be required.",
            "urgency": "Very High / Urgent"
        },
    }

    default_info = {
        "description": "Diabetic retinopathy stage detected by the AI model. Exact subclassification could not be matched to a predefined category.",
        "action": "Please correlate with clinical findings and imaging. A comprehensive ophthalmic examination is recommended.",
        "urgency": "To be decided by treating ophthalmologist"
    }

    info = severity_info.get(severity_label_clean, default_info)

    # Confidence interpretation
    if confidence >= 0.90:
        confidence_comment = "High confidence in the predicted severity classification."
    elif confidence >= 0.75:
        confidence_comment = "Moderate-to-high confidence in the predicted severity classification."
    elif confidence >= 0.60:
        confidence_comment = "Moderate confidence in the predicted severity classification; clinical correlation is important."
    else:
        confidence_comment = "Low confidence in the predicted severity classification; repeat imaging and careful clinical correlation are advised."

    # Risk level derived from severity and urgency
    risk_level = info["urgency"]

    # Timestamp for report
    generated_on = datetime.now().strftime("%Y-%m-%d %H:%M")

    report = f"""
Diabetic Retinopathy Analysis Report
------------------------------------

1. Patient / Study Information
   - Study Type       : Retinal fundus image analysis
   - Condition Focus  : Diabetic Retinopathy (DR)
   - Report Generated : {generated_on}

2. Automated AI Assessment
   - Predicted DR Severity : {severity_label_clean or "Not specified"}
   - Model Confidence      : {confidence:.4f} (0–1 scale)
   - Risk Level (AI-based) : {risk_level}

3. Interpretation of Severity
   {info["description"]}

4. Confidence Commentary
   {confidence_comment}

5. Recommended Clinical Action
   {info["action"]}

6. General Clinical Notes
   - This output is generated by an AI-based deep learning model trained on retinal images.
   - The prediction is intended to assist, not replace, a comprehensive clinical evaluation.
   - Final diagnosis and treatment decisions must be made by a qualified ophthalmologist or eye-care specialist.
   - Image quality (focus, illumination, artifacts) can significantly influence automated assessment.

7. Disclaimer
   - This report is for educational and decision-support purposes only.
   - It should not be used as the sole basis for diagnosis, screening, or treatment.
   - Always correlate with clinical history, physical examination, and additional diagnostic tests as necessary.
"""

    # Strip leading/trailing blank lines for a cleaner file
    return report.strip()  # keeps internal formatting
